README.md
README_en.md

improve readme for kubeconfig

---

README_en.md

避免Error: incompatible versions

Update Tiller version

---

README.md

many user can't clear and have more pain to install k8s,
use this tip can help fans to easy debug k8s on mac install process.
enjoy it. thanks

add tips for mac docker desktop setup process

---

README.md
images.properties

https://github.com/kubernetes/ingress-nginx/commit/78d6ce6e6e7d77309bc1e8a563e4ee5308db5566#diff-ece47c896e4784f05aa37ced8ad31c5e

fix broken links

---

images.properties

docker desktop v2.1.0.4 kubernetes v1.14.7

---

images.properties

Reverts AliyunContainerService/k8s-for-docker-desktop#52
Actually I want to push a new  branch V1.14.7 to the origin, 
There is no need to merge into the master.
The master is already v1.15.4

Revert "docker desktop v2.1.0.4 kubernetes v1.14.7"

---

README.md
README_en.md
images.properties
kubernetes-dashboard.yaml

support Kubernetes v1.14.7

---

getLatestIstio.ps1

get istio version  automatically

---

kubernetes-dashboard.yaml

kubernetes-dashboard-amd64:v1.10.1 mirror repeated download

style:mirror repeated download

---

README.md

fix install igress ->status code 404

---

README.md

fix helm status

---

README.md

查看 wordpress 发布状态：
应该由helm install wordpress stable/wordpress改为helm status wordpress

v1.16.5分支README.md文本错误

---

images.properties

Docker desktop 2.5.0.0 (Kubernetes v1.19.3)

---

images.properties

k8s v1.19.3，use coredns v1.7.0

Update images.properties coredns:1.7.0

---

images.properties

Update 1.21 coredns image path

---

images.properties

:wrench: v1.22.5

---

kubernetes-dashboard.yaml

Avoid dashboard startup failures caused by re-pulling images
#207

change dashboard imagePullPolicy to ifNotPresent

---

images.properties

Support v1.25.2

---

README.md
README_en.md

**I am a new learner of k8s, so this PR could be wrong. Please inspect the changes carefully.**
Corresponding to the installation process, there should be a local way to delete ingress.

Add a local way to delete ingress

---

README.md

Update Istio to latest version

---

kubernetes-dashboard.yaml

when start dashboard, use registry.cn-hangzhou.aliyuncs.com image to avoid pull image timeout

fix denverdino##237
